# zsh-defer is optional - configuration will work without it
if [ -f ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh ]; then
  source ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh
  ZSH_DEFER_AVAILABLE=true
else
  ZSH_DEFER_AVAILABLE=false
fi

files=(
  aliases
  bindkeys
  colors
  completion
  functions
  history
  locale
  options
  prompt
  plugins
)

for file in $files; do
  source ~/.zsh/$file.zsh
done

autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

alias dev="/Users/parker/Developer/mono/dev"


. "$HOME/.atuin/bin/env"

eval "$(atuin init zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
