cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'

# brew install
brew 'node'
brew 'awscli'
brew 'git'
brew 'python3'
brew 'ruby'
brew 'yarn'
brew 'postgresql'
brew 'mongodb'
brew 'wifi-password'

# Cask installs

# General Apps
cask 'google-chrome'
cask 'firefox'
cask 'dropbox'
cask 'bartender'
cask '1password'
cask 'spotify'
cask 'slack'
cask 'transmission'
cask 'little-snitch'
cask 'linkliar'
cask 'vlc'
cask 'grammarly'
cask 'sip'
cask 'droplr'
# Development Apps
cask 'vscode'
cask 'iterm2'
cask 'sourcetree'
cask 'docker'
cask 'kitematic'
cask 'paw'
cask 'postman'
cask 'now'
cask 'dash'
cask 'github'
cask 'graphql-ide'
cask 'gitscout'
# Design Apps
cask 'sketch'
cask 'abstract'
cask 'iconjar'
cask 'adobe-creative-cloud'
cask 'framer'
cask 'framer-x'
cask 'figma'
cask 'rightfont'
cask 'origami-studio'
cask 'principle'
cask 'protopie'
cask 'unity'
cask 'zeplin'