#!/usr/bin/env sh

# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=dock_did_restart action="yabai -m config window_shadow float"

yabai -m config top_padding                                     0
yabai -m config bottom_padding                                  0
yabai -m config left_padding                                    0
yabai -m config right_padding                                   0
yabai -m config window_gap                                      4

yabai -m config layout                                          bsp
yabai -m config mouse_follows_focus                             off
yabai -m config focus_follows_mouse                             off
yabai -m config window_placement                                second_child
yabai -m config window_shadow                                   float
yabai -m config split_ratio                                     0.70
yabai -m config mouse_modifier                                  ctrl
yabai -m config mouse_drop_action                               stack
yabai -m config mouse_action1                                   move
yabai -m config mouse_action2                                   resize

yabai -m rule --add app="System Preferences"                    manage=off
yabai -m rule --add app="About This Mac"                        manage=off
yabai -m rule --add app="App Store"                             manage=off
yabai -m rule --add app="Activity Monitor"                      manage=off
yabai -m rule --add app="Preview"                               manage=off
yabai -m rule --add app="zoom.us"                               manage=off
yabai -m rule --add app="Spotify"                               manage=off
yabai -m rule --add app="CleanShot X"                           manage=off
yabai -m rule --add app="Loom"                                  manage=off
yabai -m rule --add app="Things 3"                              manage=off

yabai -m rule --add app="Ghostty"                               space=^1
yabai -m rule --add app="Dia"                                   space=^2
yabai -m rule --add app="Linear"                                space=^2
yabai -m rule --add app="Discord"                               space=^3
yabai -m rule --add app="Amie"                                  space=^3
yabai -m rule --add app="Slack"                                 space=^3
yabai -m rule --add app="Mimestream"                            space=^3
yabai -m rule --add app="Texts"                                 space=^3
yabai -m rule --add app="Obsidian"                              space=^3
yabai -m rule --add app="Figma Beta"                            space=^4

yabai -m space 2 --layout stack
yabai -m space 3 --layout stack

echo "yabai configuration loaded..."
